export const CREATE_PROJECT_FORM_SENT = "CREATE_PROJECT_FORM_SENT";
export const PROJECT_CREATED_SUCCESSFULLY = "PROJECT_CREATED_SUCCESSFULLY";
export const ERROR_ON_CREATING_PROJECT = "ERROR_ON_CREATING_PROJECT";
export const CLEAN_UP_STATE_CREATE_PROJECT = "CLEAN_UP_STATE_CREATE_PROJECT";