export const STREAM_LIST_REQUEST_SENT = "STREAM_LIST_REQUEST_SENT";
export const STREAM_LIST_DATA_RECEIVED = "STREAM_LIST_DATA_RECEIVED";
export const STREAM_DETAIL_REQUEST_SENT = "STREAM_DETAIL_REQUEST_SENT";
export const STREAM_DETAIL_DATA_RECEIVED = "STREAM_DETAIL_DATA_RECEIVED";
export const CREATE_NEW_STREAM_FROM_STREAM_REQUEST_SENT = "CREATE_NEW_STREAM_FROM_STREAM_REQUEST_SENT";
export const CREATE_NEW_STREAM_FROM_STREAM_DATA_RECEIVED = "CREATE_NEW_STREAM_FROM_STREAM_DATA_RECEIVED";