export const TOPIC_LIST_REQUEST_SENT = "TOPIC_LIST_REQUEST_SENT";
export const TOPIC_LIST_DATA_RECEIVED = "TOPIC_LIST_DATA_RECEIVED";
export const TOPIC_SCHEMA_REQUEST_SENT = "TOPIC_SCHEMA_REQUEST_SENT";
export const TOPIC_SCHEMA_DATA_RECEIVED = "TOPIC_SCHEMA_DATA_RECEIVED";
export const CREATE_NEW_STREAM_FROM_TOPIC_REQUEST_SENT = "CREATE_NEW_STREAM_FROM_TOPIC_REQUEST_SENT";
export const CREATE_NEW_STREAM_FROM_TOPIC_DATA_RECEIVED = "CREATE_NEW_STREAM_FROM_TOPIC_DATA_RECEIVED";