name: test

on:
  pull_request:
    branchs:
      - master
  push:
    branchs:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: ['3.7', '3.8']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Poetry
        run: |
          curl -sSL "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py" | python
      - name: Install dependencies
        run: |
          source "$HOME/.poetry/env"

          poetry config virtualenvs.in-project true
          poetry install
      - name: Run tests
        run: |
          source "$HOME/.poetry/env"

          poetry run flake8 .
          poetry run black --check kamui
          poetry run mypy kamui
          poetry run pytest
          poetry run poetry check
          poetry run pip check
